### ISSUE TITLE
Revmet_example error: minion_read_bin_from_perc_cov.py

### ISSUE THREAD

**Issue by NLoustalot** [nedpeel/RevMet#1]
Hi,

I really enjoyed your article! Wanting to see how it works, I tried to run the code example you posted.
Everything runs smoothly until the minion_read_bin_from_perc_cov.py program. I always get the same issue

`Traceback (most recent call last):
  File "revmet_example/scripts/minion_read_bin_from_perc_cov.py", line 25, in <module>
    if pc > dict[minion_read_id][dict[minion_read_id].keys()[0]]:
TypeError: 'dict_keys' object is not subscriptable`

Not a python master myself, I could not figure out what it means nor how to fix it.
I tried running the revmet_example.sh scrypt line by line. I get the mock_mix_1_1.ids file (600 lines; which I believe is to expected) but then get the same error message.

I tried to run it on python 2.7, 3.8 and 3.9. Nothing changes. I wonder then if it could be something I did or install wrong? A crucial step I missed before running revmet_example.sh?

Any help would be appreciated.

Thanks 
Nathan

**Comment by nedpeel** [comment]
Hi Nathan,

Glad you liked the article and thanks for raising this issue.

I was unable to replicate the error with python 2.7, but did receive the error with python 3.

In python 3, dict.keys() are iterable but not indexable, so I've fixed the issue by making those cases indexable by using list() e.g. list(dict.keys())

I've updated the minion_read_bin_from_perc_cov.py script and tested the pipeline with python 3. Everything seems to be working fine now.

Please let me know if you run into any other issues and if you have any other questions about RevMet feel free to email me.

Kind regards,
Ned

**Comment by NLoustalot** [comment]
Hi Ned,

It did sort the issue indeed.

Thank you very much!

Best regards,
Nathan
